worklog = {'TITLE': 'Work Logger',
           'H': 1000,
           'W': 300,
           'FONT': 'Tahoma',
           'FONT_SIZE': 20,
           'REL_H': 0.07,
           'BORDER': 0,
           'SPACE': 0.06,
           'REL_W': 0.92,
           'REL_X': 0.04,
           'BACKGROUND_COLOR': '#435363',
           'FONT_COLOR': '#ffffff',
           'BUTTON_COLOR': '#dbd9d6'}

feedback = {'TITLE': 'Information',
            'H': 247,
            'W': 400,
            'FONT': 'Tahoma',
            'FONT_SIZE': 20,
            'BORDER': 0,
            'BACKGROUND_COLOR': '#435363',
            'FONT_COLOR': '#ffffff',
            'REL_X': 0.04,
            'REL_W': 0.92,
            'REL_H': 0.6}
